### ISSUE TITLE
Feature: Add async support

### ISSUE THREAD

**Issue by WASasquatch** [FHPythonUtils/SvgTrace#3] opened 2023-04-07 21:49 UTC
```
[/usr/local/lib/python3.9/dist-packages/svgtrace/__init__.py](https://localhost:8080/#) in trace(filename, blackAndWhite, mode)
     39                 raise FileNotFoundError(f"{filename} does not exist!")
     40 
---> 41         with sync_playwright() as p:
     42                 install(p.chromium)
     43 		browser = p.chromium.launch(

[/usr/local/lib/python3.9/dist-packages/playwright/sync_api/_context_manager.py](https://localhost:8080/#) in __enter__(self)
     45             self._own_loop = True
     46         if self._loop.is_running():
---> 47             raise Error(
     48                 """It looks like you are using Playwright Sync API inside the asyncio loop.
     49 Please use the Async API instead."""

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

What's this about? Is this not even performing operations locally?

**Comment by gustavobhz** [comment] 2023-04-08 17:35
Similar problem with Playwright: (Python >= 3.8) when import trace from svgtrace:

Traceback (most recent call last):
  File "xpto.py", line 4, in <module>
    from svgtrace import trace
  File "/usr/local/lib/python3.8/dist-packages/svgtrace/__init__.py", line 11, in <module>
    from install_playwright import install
  File "/usr/local/lib/python3.8/dist-packages/install_playwright/__init__.py", line 6, in <module>
    from playwright.async_api import BrowserType as AsyncBrowserType
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 36, in <module>
    from pyee.asyncio import AsyncIOEventEmitter
ModuleNotFoundError: No module named 'pyee.asyncio'

**Comment by FredHappyface** [comment] 2023-06-24 16:10
> What's this about? Is this not even performing operations locally?

Yup, what happens is it runs some js in a headless web browser. Not an elegant solution but the one I went for. 

> Error: It looks like you are using Playwright Sync API inside the asyncio loop.

svgtrace soes use the Playwright Sync API inside a synchrounous function. I'll update this to a feature as that is a good feature request tbh. Are you calling the synchronous function from async code such as asyncio?

> Similar problem with Playwright: (Python >= 3.8) when import trace from svgtrace:

Hmm interesting, this looks to be caused by a different component (playwright). May be best to report this to them so they can better track this

**Comment by FredHappyface** [comment] 2023-06-25 21:48
Fixed in https://github.com/FHPythonUtils/SvgTrace/releases/tag/2023.1

**Closed as completed by FredHappyface** 2023-06-25 21:48 UTC
Labels: enhancement
